# Generated by Django 2.1.5 on 2022-09-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=100)),
                ('person_name', models.TextField(max_length=100)),
                ('police_station', models.TextField(max_length=100, null=True)),
                ('district_name', models.TextField(max_length=100, null=True)),
                ('person_contact', models.IntegerField(max_length=100, null=True)),
                ('GD_Case_no', models.IntegerField(max_length=100, null=True)),
                ('GD_Case_date', models.TextField(max_length=100, null=True)),
                ('officer_no', models.IntegerField(max_length=100, null=True)),
                ('photo', models.ImageField(upload_to='static\\photos')),
            ],
        ),
    ]
