# Generated by Django 2.1.5 on 2022-10-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedata',
            old_name='GD_Case_date',
            new_name='GD_case_date',
        ),
        migrations.RenameField(
            model_name='imagedata',
            old_name='GD_Case_no',
            new_name='GD_case_no',
        ),
        migrations.AddField(
            model_name='imagedata',
            name='lost_found',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='upload_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
