# Generated by Django 2.1.5 on 2022-10-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20221001_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='lost_found',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
