# Generated by Django 2.1.5 on 2022-10-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20221001_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='is_matched',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='matched_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
