# Generated by Django 2.1.5 on 2022-11-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20221114_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='feats',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
